/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.main;

import com.raven.component.BreadcrumbItem;
import com.raven.event.EventItemSelected;
import javax.swing.JOptionPane;

/**
 *
 * @author RAVEN
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        breadcrumb1.addItem("Item 1");
        breadcrumb1.addItem("Item 2");
        breadcrumb1.addItem("Item 3");
        breadcrumb1.addItem("Item 4");
        breadcrumb1.addItem("Item 5");
        breadcrumb1.addItem("Item 6");
        breadcrumb1.setEvent(new EventItemSelected() {
            @Override
            public void selected(BreadcrumbItem item) {
                JOptionPane.showMessageDialog(Main.this, item.getIndex());
            }
        });
        breadcrumb2.addItem("Item 1");
        breadcrumb2.addItem("Item 2");
        breadcrumb2.addItem("Item 3");
        breadcrumb2.addItem("Item 4");
        breadcrumb2.addItem("Item 5");
        breadcrumb2.addItem("Item 6");
        breadcrumb2.setEvent(new EventItemSelected() {
            @Override
            public void selected(BreadcrumbItem item) {
                JOptionPane.showMessageDialog(Main.this, item.getIndex());
            }
        });
        breadcrumb3.addItem("Item 1");
        breadcrumb3.addItem("Item 2");
        breadcrumb3.addItem("Item 3");
        breadcrumb3.addItem("Item 4");
        breadcrumb3.addItem("Item 5");
        breadcrumb3.addItem("Item 6");
        breadcrumb3.setEvent(new EventItemSelected() {
            @Override
            public void selected(BreadcrumbItem item) {
                JOptionPane.showMessageDialog(Main.this, item.getIndex());
            }
        });
        breadcrumb4.addItem("Item 1");
        breadcrumb4.addItem("Item 2");
        breadcrumb4.addItem("Item 3");
        breadcrumb4.addItem("Item 4");
        breadcrumb4.addItem("Item 5");
        breadcrumb4.addItem("Item 6");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        breadcrumb2 = new com.raven.component.Breadcrumb();
        breadcrumb3 = new com.raven.component.Breadcrumb();
        breadcrumb1 = new com.raven.component.Breadcrumb();
        breadcrumb4 = new com.raven.component.Breadcrumb();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(255, 255, 255));

        breadcrumb2.setForeground(new java.awt.Color(255, 255, 255));
        breadcrumb2.setColor1(new java.awt.Color(0, 82, 212));
        breadcrumb2.setColor2(new java.awt.Color(111, 177, 252));
        breadcrumb2.setColorSelected(new java.awt.Color(255, 255, 255));

        breadcrumb3.setForeground(new java.awt.Color(255, 255, 255));
        breadcrumb3.setColor1(new java.awt.Color(0, 0, 70));
        breadcrumb3.setColor2(new java.awt.Color(28, 181, 224));
        breadcrumb3.setColorSelected(new java.awt.Color(255, 255, 255));

        breadcrumb1.setBackground(new java.awt.Color(255, 255, 255));
        breadcrumb1.setForeground(new java.awt.Color(255, 255, 255));
        breadcrumb1.setColor1(new java.awt.Color(74, 0, 224));
        breadcrumb1.setColor2(new java.awt.Color(172, 88, 245));
        breadcrumb1.setColorSelected(new java.awt.Color(255, 255, 255));

        breadcrumb4.setForeground(new java.awt.Color(89, 89, 89));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel1.setText(" Support me by subscribe");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(breadcrumb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(breadcrumb4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(breadcrumb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(breadcrumb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(816, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(breadcrumb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(breadcrumb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(breadcrumb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(breadcrumb4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.component.Breadcrumb breadcrumb1;
    private com.raven.component.Breadcrumb breadcrumb2;
    private com.raven.component.Breadcrumb breadcrumb3;
    private com.raven.component.Breadcrumb breadcrumb4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
